import React from 'react'

import * as unistyles from '../web/services'
import { error, isServer } from '../web/utils'
import { resetServerUnistyles } from './resetServerUnistyles'

type ServerUnistylesStylesProps = {
    nonce?: string
}

/**
 * Flushes styles generated by preceding custom DOM siblings.
 *
 * Transformed React Native hosts emit their own RSC stylesheet resources. Use
 * this fallback after custom DOM styled through getWebProps.
 */
export const ServerUnistylesStyles = ({ nonce }: ServerUnistylesStylesProps) => {
    if (!isServer()) {
        throw error('Server styles should only be read on the server')
    }

    const css = unistyles.services.registry.css.getStyles()

    resetServerUnistyles()

    if (!css) {
        return null
    }

    return <style nonce={nonce}>{css}</style>
}
