import type { Plugin } from 'vite'

import { NATIVE_COMPONENTS_PATHS, REACT_NATIVE_COMPONENT_NAMES } from '../../plugin/src/consts'

const nativeComponents = [
    ...REACT_NATIVE_COMPONENT_NAMES,
    ...NATIVE_COMPONENTS_PATHS.imports.map((component) => component.mapTo),
].map((component) => `react-native-unistyles/components/native/${component}`)

/**
 * Prebundles the deep imports generated by the React Native Unistyles Babel plugin.
 *
 * Vite scans dependencies before Babel rewrites React Native component imports,
 * so every environment must know about these generated imports.
 */
export const unistyles = (): Plugin => ({
    name: 'react-native-unistyles',
    configEnvironment() {
        return {
            optimizeDeps: {
                include: nativeComponents,
            },
        }
    },
})
